
let token=localStorage.getItem("token")||""; let me=null;
const $=id=>document.getElementById(id);
async function api(url,opt={}){let r=await fetch(url,{...opt,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(opt.headers||{})}});let j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Hata");return j}
function toast(m){$("toast").innerText=m;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2800)}
function isLoggedIn(){return !!token}
function page(id){ if(id==="auth"&&isLoggedIn()) id="panel"; document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(id).classList.add("active"); if(id==="packages")loadPackages(); if(id==="panel")dash(); if(id==="movies"){movies();ceo()} if(id==="admin")admin();}
function refreshMenu(){ $("loginTop").classList.toggle("hidden",isLoggedIn()); $("logoutBtn").classList.toggle("hidden",!isLoggedIn()); $("adminNav").classList.toggle("hidden",!(me&&me.role==="admin")); }
function logout(){localStorage.removeItem("token");token="";me=null;refreshMenu();page("home");toast("Çıkış yapıldı")}
async function init(){try{if(token){let d=await api("/api/me");me=d.user;refreshMenu();}}catch(e){logout()} loadPackages(); refreshMenu();}
async function loadPackages(){let p=await api("/api/packages");$("packageList").innerHTML=p.map(x=>`<div class="package"><span class="badge">${x.badge}</span><h3>${x.name}</h3><div class="price">${x.price} TL</div><p>${x.depth} seviye referans | %${x.rate*100} prim</p><ul>${x.features.map(f=>`<li>${f}</li>`).join("")}</ul><button onclick="choosePack(${x.id},${x.price})">Paketi Seç</button></div>`).join("");}
function choosePack(id,price){page("panel");setTimeout(()=>{let s=$("packSel"); if(s){s.value=id;$("payAmount").value=price}},300)}
async function register(){try{await api("/api/register",{method:"POST",body:JSON.stringify({firstName:rf.value,lastName:rl.value,email:re.value,phone:rp.value,password:rs.value,password2:rs2.value,referralCode:rr.value})});toast("Kayıt başarılı, giriş yapın")}catch(e){toast(e.message)}}
async function login(){try{let d=await api("/api/login",{method:"POST",body:JSON.stringify({email:le.value,password:ls.value})});token=d.token;me=d.user;localStorage.setItem("token",token);refreshMenu();toast("Giriş başarılı");page("panel")}catch(e){toast(e.message)}}
async function dash(){try{let d=await api("/api/dashboard");me=d.user;refreshMenu();let packs=await api("/api/packages");$("dash").innerHTML=`<div class="panelGrid"><div class="box">Çekilebilir Bakiye<br><b>${d.user.balance} TL</b></div><div class="box">Paket<br><b>${d.package?d.package.name:"Aktif Değil"}</b></div><div class="box">Alt Üye<br><b>${d.children.length}</b></div></div><div class="card"><h3>Referans Sistemi</h3><div class="refBox"><span class="refCode" id="refCode">${d.user.referralCode}</span><button onclick="copyRef()">Kopyala</button><button onclick="shareRef()">Paylaş</button></div></div><div class="card"><h3>IBAN Ödeme Bildir</h3><p><b>IBAN:</b> TR78 0015 7000 0000 0037 7980 62<br><b>Alıcı:</b> YILMAZ ORAL<br><b>Açıklama:</b> Telefon numaranızı yazınız</p><select id="packSel">${packs.map(p=>`<option value="${p.id}" data-price="${p.price}">${p.name} - ${p.price} TL</option>`).join("")}</select><input id="payAmount" placeholder="Tutar"><input id="payPhone" value="${d.user.phone}" placeholder="Telefon"><button onclick="payment()">Ödeme Bildir</button></div><div class="card"><h3>Çekim Talebi</h3><input id="wName" value="${d.user.firstName} ${d.user.lastName}" placeholder="Ad Soyad"><input id="wIban" placeholder="IBAN"><input id="wAmount" placeholder="50 TL ve katları"><button onclick="withdraw()">Çekim Talebi Gönder</button></div><div class="card"><h3>Alt Üyelerim</h3>${d.children.map(c=>`<p>👤 ${c.firstName} ${c.lastName} - ${c.phone}</p>`).join("")||"Alt üye yok"}</div><div class="card"><h3>Kazanç Geçmişi</h3>${d.tx.map(t=>`<p>${t.amount} TL - ${t.desc}</p>`).join("")||"İşlem yok"}</div>`;packSel.onchange=()=>payAmount.value=packSel.options[packSel.selectedIndex].dataset.price;payAmount.value=packSel.options[0].dataset.price;}catch(e){$("dash").innerHTML='<div class="card">Devam etmek için giriş yapmalısınız.</div>';}}
function copyRef(){navigator.clipboard.writeText($("refCode").innerText);toast("Referans kodu kopyalandı")}
function shareRef(){let code=$("refCode").innerText;let text=`İzleKazan referans kodum: ${code}`; if(navigator.share) navigator.share({text}); else {navigator.clipboard.writeText(text);toast("Paylaşım metni kopyalandı")}}
async function payment(){try{await api("/api/payment",{method:"POST",body:JSON.stringify({packageId:packSel.value,amount:payAmount.value,phone:payPhone.value,note:payPhone.value})});toast("Ödeme bildirimi gönderildi")}catch(e){toast(e.message)}}
async function withdraw(){try{await api("/api/withdraw",{method:"POST",body:JSON.stringify({fullName:wName.value,iban:wIban.value,amount:wAmount.value})});toast("Çekim talebi gönderildi")}catch(e){toast(e.message)}}
async function movies(){try{let m=await api("/api/movies");$("movieList").innerHTML=m.map(x=>`<div class="card movie ${x.locked?'locked':''}"><img src="${x.poster||'https://via.placeholder.com/300x450?text=Film'}"><h3>${x.title}</h3><p>${x.description||""}</p>${x.locked?'<span class="lock">Premium üyelik gerekli</span>':`<a href="${x.link}" target="_blank"><button>Filmi Aç</button></a>`}</div>`).join("")}catch(e){$("movieList").innerHTML='<div class="card">Filmleri görmek için giriş yapmalısınız.</div>'}}
async function addMovie(){try{await api("/api/movies",{method:"POST",body:JSON.stringify({title:mt.value,year:my.value,category:mc.value,poster:mp.value,link:ml.value,description:md.value})});toast("Film CEO onayına gönderildi")}catch(e){toast(e.message)}}
async function ceo(){try{let m=await api("/api/ceo/pending");$("ceoBox").innerHTML=`<div class="card"><h3>CEO Onay Paneli</h3>${m.map(x=>`<p>${x.title} <button onclick="okMovie('${x.id}')">Onayla</button><button onclick="noMovie('${x.id}')">Reddet</button></p>`).join("")||"Bekleyen film yok"}</div>`}catch(e){$("ceoBox").innerHTML=""}}
async function okMovie(id){await api("/api/ceo/approve/"+id,{method:"POST"});toast("Film onaylandı");ceo()}
async function noMovie(id){await api("/api/ceo/reject/"+id,{method:"POST"});toast("Film reddedildi");ceo()}
async function admin(){try{let d=await api("/api/admin/all");$("adminBox").innerHTML=`<h3>Ödemeler</h3>${d.payments.map(p=>`<p>${p.phone} | ${p.amount} TL | ${p.status} <button onclick="payOk('${p.id}')">Onayla</button><button onclick="payNo('${p.id}')">Reddet</button></p>`).join("")||"Ödeme yok"}<h3>Kullanıcılar</h3>${d.users.map(u=>`<p>${u.firstName} ${u.lastName} | ${u.phone} | ${u.balance} TL | Paket:${u.packageId}</p>`).join("")}<h3>Çekimler</h3>${d.withdrawals.map(w=>`<p>${w.amount} TL | ${w.status} <button onclick="wdOk('${w.id}')">Onayla</button><button onclick="wdNo('${w.id}')">Reddet</button></p>`).join("")||"Çekim yok"}`}catch(e){$("adminBox").innerHTML="Admin girişi gerekli"}}
async function payOk(id){await api("/api/admin/payments/"+id+"/approve",{method:"POST"});toast("Ödeme onaylandı");admin()}
async function payNo(id){await api("/api/admin/payments/"+id+"/reject",{method:"POST"});toast("Ödeme reddedildi");admin()}
async function wdOk(id){await api("/api/admin/withdrawals/"+id+"/approve",{method:"POST"});toast("Çekim onaylandı");admin()}
async function wdNo(id){await api("/api/admin/withdrawals/"+id+"/reject",{method:"POST"});toast("Çekim reddedildi");admin()}
init();
