
const express=require('express'), cors=require('cors'), bcrypt=require('bcryptjs'), jwt=require('jsonwebtoken'), fs=require('fs'), path=require('path');
const {v4:uuidv4}=require('uuid'); const app=express(); const PORT=process.env.PORT||3000; const SECRET=process.env.JWT_SECRET||'izlekazan-secret'; const DB=path.join(__dirname,'db.json');
app.use(cors()); app.use(express.json({limit:'2mb'})); app.use(express.static('public'));
const PACKAGES=[{id:1,name:'Üye',price:100,depth:1,rate:.10},{id:2,name:'Kıdemli Üye',price:200,depth:2,rate:.10},{id:3,name:'Ortak',price:300,depth:3,rate:.10},{id:4,name:'Kıdemli Ortak',price:500,depth:3,rate:.20},{id:5,name:'CEO',price:1000,depth:3,rate:.30}];
function now(){return new Date().toISOString()} function def(){return {users:[],payments:[],withdrawals:[],transactions:[],movies:[],logs:[],notifications:[]}};
function db(){if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(def(),null,2));return JSON.parse(fs.readFileSync(DB,'utf8'))} function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}
function pub(u){if(!u)return null; let {passwordHash,...x}=u; return x} function ref(n='IZLE'){return n.replace(/\s/g,'').slice(0,5).toUpperCase()+Math.floor(10000+Math.random()*89999)}
function tx(d,userId,amount,type,description){d.transactions.push({id:uuidv4(),userId,amount,type,description,createdAt:now()})} function log(d,actorId,action,detail){d.logs.push({id:uuidv4(),actorId,action,detail,createdAt:now()})}
function note(d,userId,message){d.notifications.push({id:uuidv4(),userId,message,read:false,createdAt:now()})}
(function admin(){let d=db(); if(!d.users.find(u=>u.email==='admin@admin.com')){d.users.push({id:uuidv4(),firstName:'Admin',lastName:'Yönetici',email:'admin@admin.com',phone:'05000000000',passwordHash:bcrypt.hashSync('123456',10),referralCode:'ADMIN',sponsorId:null,packageId:5,balance:0,role:'admin',isBanned:false,createdAt:now()}); save(d)}})();
function auth(req,res,next){let h=req.headers.authorization||'';let t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({error:'Giriş gerekli'});try{req.user=jwt.verify(t,SECRET);next()}catch(e){res.status(401).json({error:'Geçersiz oturum'})}}
function role(roles){return (req,res,next)=>{let d=db(),u=d.users.find(x=>x.id===req.user.id); if(!u||u.isBanned)return res.status(403).json({error:'Yetki yok'}); if(!roles.includes(u.role)&&!(roles.includes('ceo')&&u.packageId===5))return res.status(403).json({error:'Yetki yok'}); req.fullUser=u; next()}}
function distribute(d,buyer,amount){let sid=buyer.sponsorId; for(let level=1;level<=3;level++){if(!sid)break; let s=d.users.find(u=>u.id===sid); if(!s)break; let p=PACKAGES.find(x=>x.id===s.packageId); if(p&&level<=p.depth){let c=+(amount*p.rate).toFixed(2); s.balance=+(Number(s.balance||0)+c).toFixed(2); tx(d,s.id,c,'referral',`${buyer.firstName} ${buyer.lastName} ${level}. seviye referans`); note(d,s.id,`Referanstan ${c} TL kazandınız.`)} sid=s.sponsorId}}
app.get('/api/health',(req,res)=>res.json({ok:true,name:'İzleKazan'})); app.get('/api/packages',(req,res)=>res.json(PACKAGES));
app.post('/api/register',(req,res)=>{let {firstName,lastName,email,phone,password,password2,referralCode}=req.body; if(!firstName||!lastName||!email||!phone||!password||!password2)return res.status(400).json({error:'Tüm alanları doldurun'}); if(!email.includes('@'))return res.status(400).json({error:'Geçerli email girin'}); if(!/^0\d{10}$/.test(phone))return res.status(400).json({error:'Telefon 05XXXXXXXXX formatında olmalı'}); if(password.length<6)return res.status(400).json({error:'Şifre en az 6 karakter'}); if(password!==password2)return res.status(400).json({error:'Şifreler eşleşmiyor'}); let d=db(); if(d.users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return res.status(400).json({error:'Bu email zaten kayıtlı'}); if(d.users.some(u=>u.phone===phone))return res.status(400).json({error:'Bu telefon zaten kayıtlı'}); let sp=referralCode?d.users.find(u=>u.referralCode.toUpperCase()===String(referralCode).toUpperCase()):null; let u={id:uuidv4(),firstName,lastName,email:email.toLowerCase(),phone,passwordHash:bcrypt.hashSync(password,10),referralCode:ref(firstName),sponsorId:sp?sp.id:null,packageId:0,balance:0,role:'user',isBanned:false,createdAt:now()}; d.users.push(u); log(d,u.id,'register',`${firstName} kayıt oldu`); save(d); res.json({success:true,user:pub(u)})});
app.post('/api/login',(req,res)=>{let {email,password}=req.body,d=db(),u=d.users.find(x=>x.email.toLowerCase()===String(email||'').toLowerCase()); if(!u||!bcrypt.compareSync(password||'',u.passwordHash))return res.status(400).json({error:'Email veya şifre hatalı'}); if(u.isBanned)return res.status(403).json({error:'Hesap yasaklı'}); let token=jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'}); res.json({token,user:pub(u)})});
app.get('/api/dashboard',auth,(req,res)=>{let d=db(),u=d.users.find(x=>x.id===req.user.id); res.json({user:pub(u),children:d.users.filter(x=>x.sponsorId===u.id).map(pub),payments:d.payments.filter(p=>p.userId===u.id),withdrawals:d.withdrawals.filter(w=>w.userId===u.id),movies:d.movies.filter(m=>m.addedBy===u.id),transactions:d.transactions.filter(t=>t.userId===u.id).slice(-30).reverse(),packages:PACKAGES})});
app.get('/api/tree/:userId?',auth,(req,res)=>{let d=db(),root=req.params.userId||req.user.id,me=d.users.find(u=>u.id===req.user.id); if(root!==req.user.id&&me.role!=='admin')return res.status(403).json({error:'Yetki yok'}); function b(id){let u=d.users.find(x=>x.id===id); if(!u)return null; return {id:u.id,name:u.firstName+' '+u.lastName,phone:u.phone,balance:u.balance,packageId:u.packageId,children:d.users.filter(x=>x.sponsorId===id).map(x=>b(x.id))}} res.json(b(root))});
app.post('/api/payment',auth,(req,res)=>{let {phone,packageId,amount,note:nt}=req.body,d=db(),u=d.users.find(x=>x.phone===phone); if(!u)return res.status(400).json({error:'Bu telefon ile kullanıcı bulunamadı'}); if(u.id!==req.user.id)return res.status(403).json({error:'Telefon hesabınızla eşleşmiyor'}); if(d.payments.some(p=>p.userId===u.id&&p.status==='pending'))return res.status(400).json({error:'Bekleyen ödeme bildiriminiz var'}); let p=PACKAGES.find(x=>x.id===Number(packageId)); if(!p)return res.status(400).json({error:'Paket yok'}); if(Number(amount)!==p.price)return res.status(400).json({error:'Tutar paket fiyatıyla uyuşmuyor'}); d.payments.push({id:uuidv4(),userId:u.id,phone,packageId:p.id,amount:p.price,note:nt||phone,status:'pending',createdAt:now()}); log(d,u.id,'payment_create',`${p.name} ödeme bildirimi`); save(d); res.json({success:true})});
app.post('/api/withdraw',auth,(req,res)=>{let {iban,amount,phone,fullName}=req.body,d=db(),u=d.users.find(x=>x.id===req.user.id),a=Number(amount); if(phone!==u.phone)return res.status(400).json({error:'Telefon eşleşmiyor'}); if(!iban||!fullName)return res.status(400).json({error:'Ad soyad ve IBAN zorunlu'}); if(a<50)return res.status(400).json({error:'Minimum çekim 50 TL'}); if(a%50!==0)return res.status(400).json({error:'Sadece 50 TL ve katları'}); if(a>Number(u.balance||0))return res.status(400).json({error:'Yetersiz bakiye'}); if(d.withdrawals.some(w=>w.userId===u.id&&w.status==='pending'))return res.status(400).json({error:'Bekleyen çekim talebiniz var'}); d.withdrawals.push({id:uuidv4(),userId:u.id,fullName,phone,iban,amount:a,status:'pending',createdAt:now()}); save(d); res.json({success:true})});
app.get('/api/movie-info',auth,(req,res)=>{let id=(String(req.query.imdb||'').match(/tt\d+/)||[])[0]; if(!id)return res.status(400).json({error:'IMDB ID bulunamadı'}); res.json({imdbId:id,title:'Örnek Film',year:'2026',category:'Aksiyon, Dram',poster:'https://via.placeholder.com/300x450?text=Film',description:'TMDB API bağlanınca bilgiler otomatik dolacak. Bu test verisidir.'})});
app.post('/api/movies',auth,(req,res)=>{let {imdbId,title,year,category,poster,description,videoLink}=req.body; if(!imdbId||!title||!year||!videoLink)return res.status(400).json({error:'Film bilgileri eksik'}); let d=db(); if(d.movies.some(m=>m.imdbId===imdbId||m.videoLink===videoLink))return res.status(400).json({error:'Bu film zaten var'}); d.movies.push({id:uuidv4(),imdbId,title,year,category,poster,description,videoLink,addedBy:req.user.id,approvedBy:null,status:'pending',addRewardPaid:false,ceoRewardPaid:false,createdAt:now()}); save(d); res.json({success:true})});
app.get('/api/movies',(req,res)=>res.json(db().movies.filter(m=>m.status==='approved')));
app.get('/api/ceo/pending-movies',auth,role(['admin','ceo']),(req,res)=>res.json(db().movies.filter(m=>m.status==='pending')));
app.post('/api/ceo/movies/:id/approve',auth,role(['admin','ceo']),(req,res)=>{let d=db(),m=d.movies.find(x=>x.id===req.params.id); if(!m)return res.status(404).json({error:'Film yok'}); if(m.addedBy===req.user.id)return res.status(400).json({error:'Kendi filmini onaylayamazsın'}); m.status='approved'; m.approvedBy=req.user.id; let ad=d.users.find(u=>u.id===m.addedBy), ceo=d.users.find(u=>u.id===req.user.id); if(ad&&!m.addRewardPaid){ad.balance=+(Number(ad.balance||0)+.25).toFixed(2); tx(d,ad.id,.25,'movie_add',`${m.title} film ekleme ödülü`); m.addRewardPaid=true} if(ceo&&!m.ceoRewardPaid){ceo.balance=+(Number(ceo.balance||0)+.10).toFixed(2); tx(d,ceo.id,.10,'movie_approve',`${m.title} onay ödülü`); m.ceoRewardPaid=true} save(d); res.json({success:true})});
app.post('/api/ceo/movies/:id/reject',auth,role(['admin','ceo']),(req,res)=>{let d=db(),m=d.movies.find(x=>x.id===req.params.id); if(!m)return res.status(404).json({error:'Film yok'}); m.status='rejected'; m.approvedBy=req.user.id; save(d); res.json({success:true})});
app.get('/api/admin/summary',auth,role(['admin']),(req,res)=>{let d=db(); res.json({users:d.users.length,pendingPayments:d.payments.filter(p=>p.status==='pending').length,pendingWithdrawals:d.withdrawals.filter(w=>w.status==='pending').length,pendingMovies:d.movies.filter(m=>m.status==='pending').length,totalBalance:d.users.reduce((a,u)=>a+Number(u.balance||0),0).toFixed(2)})});
app.get('/api/admin/all',auth,role(['admin']),(req,res)=>{let d=db(); res.json({users:d.users.map(pub),payments:d.payments,withdrawals:d.withdrawals,movies:d.movies,transactions:d.transactions.slice(-100).reverse(),logs:d.logs.slice(-100).reverse(),packages:PACKAGES})});
app.post('/api/admin/payments/:id/approve',auth,role(['admin']),(req,res)=>{let d=db(),p=d.payments.find(x=>x.id===req.params.id); if(!p)return res.status(404).json({error:'Ödeme yok'}); if(p.status!=='pending')return res.status(400).json({error:'Beklemede değil'}); let u=d.users.find(x=>x.id===p.userId); p.status='approved'; p.approvedAt=now(); u.packageId=p.packageId; if(p.packageId===5)u.role='ceo'; distribute(d,u,Number(p.amount)); save(d); res.json({success:true})});
app.post('/api/admin/payments/:id/reject',auth,role(['admin']),(req,res)=>{let d=db(),p=d.payments.find(x=>x.id===req.params.id); if(!p)return res.status(404).json({error:'Ödeme yok'}); p.status='rejected'; save(d); res.json({success:true})});
app.post('/api/admin/withdrawals/:id/approve',auth,role(['admin']),(req,res)=>{let d=db(),w=d.withdrawals.find(x=>x.id===req.params.id); if(!w)return res.status(404).json({error:'Çekim yok'}); let u=d.users.find(x=>x.id===w.userId); if(w.status!=='pending')return res.status(400).json({error:'Beklemede değil'}); if(Number(u.balance)<Number(w.amount))return res.status(400).json({error:'Yetersiz bakiye'}); u.balance=+(Number(u.balance)-Number(w.amount)).toFixed(2); w.status='approved'; tx(d,u.id,-Number(w.amount),'withdraw','Çekim onaylandı'); save(d); res.json({success:true})});
app.post('/api/admin/withdrawals/:id/reject',auth,role(['admin']),(req,res)=>{let d=db(),w=d.withdrawals.find(x=>x.id===req.params.id); if(!w)return res.status(404).json({error:'Çekim yok'}); w.status='rejected'; save(d); res.json({success:true})});
app.post('/api/admin/users/:id/ban',auth,role(['admin']),(req,res)=>{let d=db(),u=d.users.find(x=>x.id===req.params.id); if(!u)return res.status(404).json({error:'Kullanıcı yok'}); u.isBanned=true; save(d); res.json({success:true})});
app.post('/api/admin/users/:id/unban',auth,role(['admin']),(req,res)=>{let d=db(),u=d.users.find(x=>x.id===req.params.id); if(!u)return res.status(404).json({error:'Kullanıcı yok'}); u.isBanned=false; save(d); res.json({success:true})});
app.listen(PORT,()=>console.log('İzleKazan çalışıyor: '+PORT));
